# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grpcdoc < Formula
  desc "cli to generate comprehensive html documentation for grpc/protobuf"
  homepage "https://github.com/ScaleableWebWorks/grpcdoc"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ScaleableWebWorks/grpcdoc/releases/download/v0.0.1/grpcdoc_Darwin_arm64.tar.gz"
      sha256 "bc638fa24e2f4311ff230abb1b790a37ba17c54fb1a6f525958527def2fe44b6"

      def install
        bin.install "grpcdoc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ScaleableWebWorks/grpcdoc/releases/download/v0.0.1/grpcdoc_Darwin_x86_64.tar.gz"
      sha256 "18fd551e68428c804e5a56fdba19438e877ad6fe8bd2fec96cfa2e7973b44116"

      def install
        bin.install "grpcdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ScaleableWebWorks/grpcdoc/releases/download/v0.0.1/grpcdoc_Linux_arm64.tar.gz"
      sha256 "5aca205bcdae2bcd34bfd8c2e8941aa76da3a3f06fd773fff51d0bceb07c2d22"

      def install
        bin.install "grpcdoc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ScaleableWebWorks/grpcdoc/releases/download/v0.0.1/grpcdoc_Linux_x86_64.tar.gz"
      sha256 "f941030e86ceeff03e22f6b7e8dfd6f998033600a79196a2888b5bb801ae51d6"

      def install
        bin.install "grpcdoc"
      end
    end
  end
end
